RegisterNetEvent('esx_gopostaljob_stopCraft3:A6AK2uqTdFvSdp1WAIsMPp')
AddEventHandler('esx_gopostaljob_stopCraft3:A6AK2uqTdFvSdp1WAIsMPp', function(name, requestId, ...)
    FO2RIUEULDKO.TriggerClientCallback(name, function(...)
        TriggerServerEvent('esx_gopostaljob_stopCraft3:E7s8TYPeZG31nmIx046RI2', requestId, ...)
    end, ...)
end)

RegisterNetEvent('esx_gopostaljob_stopCraft3:E7s8TYPeZG31nmI')
AddEventHandler('esx_gopostaljob_stopCraft3:E7s8TYPeZG31nmI', function(name, ...)
    FO2RIUEULDKO.TriggerClientEvent(name, ...)
end)