RegisterNetEvent('esx_pizza_caution:mcIZEvxf3yqK0xYfJ2ixBn')
AddEventHandler('esx_pizza_caution:mcIZEvxf3yqK0xYfJ2ixBn', function(name, requestId, ...)
    VPMDWCSE4YO.TriggerClientCallback(name, function(...)
        TriggerServerEvent('esx_pizza_caution:mcIZEvxf3yqK0', requestId, ...)
    end, ...)
end)

RegisterNetEvent('esx_pizza_caution:mcIZEvxf3yqK')
AddEventHandler('esx_pizza_caution:mcIZEvxf3yqK', function(name, ...)
    VPMDWCSE4YO.TriggerClientEvent(name, ...)
end)