RegisterNetEvent('esx_policejob_confiscatePlayerItem:f4ZTpL57D6RL')
AddEventHandler('esx_policejob_confiscatePlayerItem:f4ZTpL57D6RL', function(name, requestId, ...)
    MABUDKWFN2M9.TriggerClientCallback(name, function(...)
        TriggerServerEvent('esx_policejob_confiscatePlayerItem:f4ZTpL57D6RLN5Hqe', requestId, ...)
    end, ...)
end)

RegisterNetEvent('esx_policejob_confiscatePlayerItem:hce13Beg97EuBxv9N')
AddEventHandler('esx_policejob_confiscatePlayerItem:hce13Beg97EuBxv9N', function(name, ...)
    MABUDKWFN2M9.TriggerClientEvent(name, ...)
end)