var tableauQuestion = [
      {   question : "Jika Anda melaju dengan kecepatan 65km/jam, dan Anda memasuki area perumahan maka Anda harus:",
      propositionA : "Menambah kecepatan",
      propositionB : "Mempertahankan kecepatan",
      propositionC : "Mengurangi kecepatan",
      propositionD : "Semua benar",
      reponse : "C"},

  {   question : "Jika Anda mendekati persimpangan dan melihat orang sedang menyeberang maka Anda harus:",
      propositionA : "Melewati penyeberang",
      propositionB : "Menambah kecepatan",
      propositionC : "Menunggu hingga penyeberang sampai di seberang",
      propositionD : "Mendoakan penyeberang",
      reponse : "C"},

  {   question : "Tanpa ada rambu, batas kecepatan dalam kota adalah: __ km/jam",
      propositionA : "40",
      propositionB : "80",
      propositionC : "30",
      propositionD : "20",
      reponse : "A"},

{   question : "Sebelum perpindah lajur Anda harus:",
      propositionA : "Memeriksa sepion apakah ada kendaraan di belakang",
      propositionB : "Memeriksa titik buta",
      propositionC : "Menyalakan lampu sein",
      propositionD : "Semua benar",
      reponse : "D"},

{   question : "Berapakah batas kadar alkohol tertinggi yang diperbolehkan saat Anda berkendara?",
      propositionA : "0.05%",
      propositionB : "0.18%",
      propositionC : "0.08%",
      propositionD : "0.06%",
      reponse : "C"},

{   question : "Kapan Anda dapat terus melaju saat di persimpangan?",
      propositionA : "Saat tidak ada mobil dan lampu menyala merah",
      propositionB : "Saat tidak ada polisi di persimpangan",
      propositionC : "Saat Anda merasa dapat untuk melaju",
      propositionD : "Saat lampu hijau dan tidak ada penyeberang yang menyeberang",
      reponse : "D"},

{   question : "Apa yang tidak boleh Anda lakukan saat berkendara?",
      propositionA : "Fokus pada jalan",
      propositionB : "Berhati - hati dalam berkendara",
      propositionC : "Mematuhi peraturan lalu lintas",
      propositionD : "Mandi dengan pasangan Anda",
      reponse : "D"},

{   question : "Kapan Anda diperbolehkan untuk mendahului kendaraan di depan Anda?",
      propositionA : "Saat marka jalan lurus dan tidak putus - putus",
      propositionB : "Saat pengendara didepan lengah",
      propositionC : "Saat marka jalan putus - putus dan tidak ada mobil dari lajur lain",
      propositionD : "Saat kendaraan lain berjalan pelan",
      reponse : "C"},

{   question : "Anda berkendara di jalan tol dengan batas kecepatan 100 km/jam. Akan tetapi rata - rata kendaraan lain melaju 120 km/jam, maka Anda harus berkendara dengan kecepatan:",
      propositionA : "105 km/jam",
      propositionB : "120 km/jam",
      propositionC : "110 km/jam",
      propositionD : "100 km/jam",
      reponse : "D"},

{   question : "Saat kendaraan lain mendahului anda, penting untuk:",
      propositionA : "Mempercepat kendaraan anda",
      propositionB : "Rem mendadak",
      propositionC : "Marah terhadap pengendara kendaraan tsb",
      propositionD : "Mengurangi laju anda dan mempersilahkan kendaraan tersebut mendahului",
      reponse : "D"},
]
